export const colaboradores = [
  {
    id: 1,
    nombre: "Ana Lopez Garcia",
    area: "Recepcion",
    departamento: "Recepcion",
    puesto: "Recepcionista",
    numero: "3612",
  },
  {
    id: 2,
    nombre: "Luis Martinez",
    area: "Tecnologia",
    departamento: "Almacen",
    puesto: "Tecnico",
    numero: "2184",
  },
  {
    id: 3,
    nombre: "Maria Fuentes",
    area: "RRHH",
    departamento: "Recursos Humanos",
    puesto: "Jefe de RRHH",
    numero: "1430",
  },
];

export const equipos = [
  {
    id: 1,
    codigo: "002",
    tipo: "Tablet",
    nombre: "Samsung Tab A8",
    marca: "Samsung",
    modelo: "Tab A8",
    serie: "SN-40298347",
    proveedor: "TechSolutions SA",
  },
  {
    id: 2,
    codigo: "001",
    tipo: "Laptop",
    nombre: "Dell XPS 15",
    marca: "Dell",
    modelo: "XPS 15 9500",
    serie: "SN-4829Y047",
    proveedor: "Dell Solutions",
  },
  {
    id: 3,
    codigo: "021",
    tipo: "Computadora",
    nombre: "HP EliteDesk 800",
    marca: "HP",
    modelo: "EliteDesk 800",
    serie: "SN-12847391",
    proveedor: "TechSolutions SA",
  },
];

export const tarjetasComedor = [
  {
    id: 1,
    codigo: "TC-3612",
    nombre: "Tarjeta comedor",
    tipo: "Tarjeta comedor",
    marca: "Chiringuito",
    modelo: "Comedor",
    serie: "TC-3612",
    estadoEntrega: "Nueva / Buen estado",
    proveedor: "Recursos Humanos",
  },
  {
    id: 2,
    codigo: "TC-2184",
    nombre: "Tarjeta comedor",
    tipo: "Tarjeta comedor",
    marca: "Chiringuito",
    modelo: "Comedor",
    serie: "TC-2184",
    estadoEntrega: "Buen estado",
    proveedor: "Recursos Humanos",
  },
  {
    id: 3,
    codigo: "TC-1430",
    nombre: "Tarjeta comedor",
    tipo: "Tarjeta comedor",
    marca: "Chiringuito",
    modelo: "Comedor",
    serie: "TC-1430",
    estadoEntrega: "Nueva / Buen estado",
    proveedor: "Recursos Humanos",
  },
];

export const yubikeys = [
  {
    id: 1,
    codigo: "YK-8821",
    nombre: "YubiKey 5 NFC",
    tipo: "Yubikey",
    marca: "Yubico",
    modelo: "5 NFC",
    serie: "YK-8821",
    proveedor: "Sistemas",
  },
  {
    id: 2,
    codigo: "YK-9034",
    nombre: "YubiKey 5C NFC",
    tipo: "Yubikey",
    marca: "Yubico",
    modelo: "5C NFC",
    serie: "YK-9034",
    proveedor: "Sistemas",
  },
  {
    id: 3,
    codigo: "YK-7740",
    nombre: "YubiKey Bio",
    tipo: "Yubikey",
    marca: "Yubico",
    modelo: "Bio",
    serie: "YK-7740",
    proveedor: "Sistemas",
  },
];
